### ISSUE TITLE
Undefined for team names when using @

### ISSUE THREAD

**Issue by olivierlambert** [NodeBB/NodeBB#13843]
### NodeBB version

v4.7.1

### NodeBB git hash

afb88805876ffba3c1f82c482245cf804c3f8eef

### NodeJS version

v22.20.0

### Exact steps to cause this issue

Since the last 2 or 3 releases, when I start to complete the name of a group in NodeBB, I have "undefined" displayed instead of the name of the group. If I paste myself the name of the group, it works (notifying the group members etc.).

See:

<img width="267" height="360" alt="Image" src="https://github.com/user-attachments/assets/3d8d2e3a-b8cd-4134-b613-f38b2a935e22" />

### What you expected

Having the team name auto completed.

**Comment by olivierlambert** [comment]
Hi @barisusakli 

So one problem is fixed, I can see the list of teams now, but when I select one, instead of having the "URL name" I have the regular name, which doesn't link to the team.

Eg:

<img width="463" height="360" alt="Image" src="https://github.com/user-attachments/assets/5d717107-f010-4b63-8c37-7228c6296019" />

But then:

<img width="833" height="150" alt="Image" src="https://github.com/user-attachments/assets/c17a178c-0543-47fc-aed4-09bd4441d4a9" />

While it should be `@team-devops` (see https://xcp-ng.org/forum/groups/team-devops)

**Comment by barisusakli** [comment]
@olivierlambert thanks for reporting looks like it was still broken on groups with whitespace.

https://github.com/julianlam/nodebb-plugin-mentions/commit/26c82bf87f6fdbbe6c2e87d63fb212addc57e7d4

<img width="1311" height="155" alt="Image" src="https://github.com/user-attachments/assets/27941421-95b0-40c9-a651-a18950dafea0" />
