### ISSUE TITLE
OpenShift Installation Guide unclear

### ISSUE THREAD

**Issue by altembo** [NodeBB/NodeBB#3159]
Hi,

for a total greenhorn to NodeBB and OpenShift it is absolutely unclear how to correctly deploy NodeBB to OpenShift, as the Steps 6, 7 & 12 are totally out of scope. 

**Step 6:**
> cd nodebb && git remote add upstream -m master https://github.com/NodeBB/NodeBB.git

.. "cd nodebb" implies I am on my local Machine ... but where should I add the upstream to? There is no Step which tells me where to init or clone a repo.
The same goes for **Step 7**

**Step 12:**
> git commit -a -m 'message' && git push

... Okay thats cool, but wait ... where I should push the changes to? I did not set up or clone any Git repository while following this Guide.

Kind Regards,
Al

**Comment by Firelad97** [comment]
Ok. Seeing this, I'm editing it now.

**Comment by Firelad97** [comment]
Done - just did do this commit #94df914
Hopefully it's more clear now.

**Comment by psychobunny** [comment]
@altembo, can you confirm if the updated steps work for you? I'm closing this issue and merging the above PR, please repost an issue on the docs repo if it doesn't work for you. Thanks

**Comment by altembo** [comment]
@Firelad97 
I am sorry, but it is still not clear to me :D Step 6 still says "cd nodebb" and I guess you are talking about changing to a directory "nodebb" within the OpenShift-App. First, there is no nodebb directory in my OpenShift App and second, Step 5 tells me to exit SSH, but I guess I have to clone the repository while on my OpenShift-App-SSH session? 
While browsing through the OpenShift-App directoris I guess I have to check out the NodeBB source from Github to MyOpenShiftApp/app-root/repo ? Is that right?

@psychobunny @Firelad97 
Thanks for you help in advance and sorry for asking such noob questions ;-)

**Comment by altembo** [comment]
Okay sorry, I didnt recognize the local NodeBB directory after creating the OpenShift App, because I already checked out the Source before. I will head back to you after I did the installation again ;-)

**Comment by altembo** [comment]
Installation worked for me, thanks for your time folks.

**Comment by psychobunny** [comment]
Great! And thanks @firelad87

**Comment by Firelad97** [comment]
No problem, glad to help.
