### ISSUE TITLE
Toggle Block getting stuck in cache?

### ISSUE THREAD

**Issue by uplift** [NodeBB/NodeBB#6643]
When searching for a user and clicking the toggle block button, the list isnt being updated to show that the user has been blocked even tho the database is correctly showing them as blocked. This causes the user to click toggle block again which then shows the user in the blocked list but the database no longer has them as blocked.

The refreshList function calls the API version of the blocks page to get the data but it looks like the cache isn't updated with the new data so shows the wrong list on the page.

**Comment by julianlam** [comment]
Are you on latest? I believe I fixed this just last week

**Comment by julianlam** [comment]
https://github.com/NodeBB/NodeBB/commit/a34584e8f5f78a64fd2f1d99e3d02dba7190ad8b

Should be in 1.10.1

**Comment by uplift** [comment]
Yes updated to 1.10.1 yesterday on our test environments. That change is in the release too but still getting the issue.

**Comment by uplift** [comment]
Does it need parseInt's round these two lines?

https://github.com/NodeBB/NodeBB/blob/a34584e8f5f78a64fd2f1d99e3d02dba7190ad8b/src/user/blocks.js#L76
https://github.com/NodeBB/NodeBB/blob/a34584e8f5f78a64fd2f1d99e3d02dba7190ad8b/src/user/blocks.js#L89

**Comment by julianlam** [comment]
It's ok I already got that. Something else is the problem.

**Comment by uplift** [comment]
I wrapped it round the uids on Line 77 and 90 too and it seems to fix the issue for me locally at least

**Comment by julianlam** [comment]
Looks like @barisusakli's commit fixed it. I thought there was another issue but I can't seem to reproduce it at the moment.
