### ISSUE TITLE
404s for /assets/client-noskin.css and /assets/src/client/404.js

### ISSUE THREAD

**Issue by tom-rade** [NodeBB/NodeBB#7274]
- **NodeBB version:** v1.11.1
- **NodeBB git hash:** 40637828af9ef89441666259326d0125a85a1b6d

- **Database type:** mongo
- **Database version:** v4.0.5

Users apparently get 404s for these paths, maybe this is a bug?
```
/assets/client-noskin.css
/assets/src/client/404.js
```

**Comment by tom-rade** [comment]
@julianlam Not sure if relevant, but also

`/assets/src/client/confirm.js`

is 404ed

**Comment by julianlam** [comment]
Are you able to reproduce `client-noskin.css`? I am not, could be that it was fixed already. If the error counter doesn't go up, then it was probably something that happened before but has since been fixed.

**Comment by tom-rade** [comment]
@julianlam Thank you! I didn't update when you did the commit. I have no errors now, great!

**Comment by tom-rade** [comment]
@julianlam Nevermind, it still appears as a 404:

`/assets/client-noskin.css`

Please reopen the issue.

**Comment by julianlam** [comment]
Don't know how to trigger it.

**Comment by tom-rade** [comment]
@julianlam /assets/src/client/registerComplete.js For example was definitely fixed. I suppose all /client paths (judging by the commit). But this one is just /assets/client-noskin.css (without /client). Maybe that helps.

I'll try to look into it, currently random users are producing this 404. In a couple of minutes already 5 404s happened.

**Comment by julianlam** [comment]
The client js issue was a different bug, so best to open a new one for client-noskin. Are you using a custom theme? It probably needs theme fixed outlined in #7266

**Comment by tom-rade** [comment]
@julianlam Found a way to reproduce it. #7276

I'm using the default Persona theme
